## Library requirements
suppressPackageStartupMessages(library(janitor, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(tidyr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(tibble, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(progress, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(data.tree, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(dplyr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
options(dplyr.summarise.inform = FALSE)
suppressPackageStartupMessages(library(corrr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(tibble, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(purrr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(ranger, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(readr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(vroom, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(tidyselect, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(recipes, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(ggplot2, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(tidymodels, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(fastshap, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(shapviz, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(doParallel, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(foreach, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(doParallel, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(glmnet, quietly = T, verbose = F, warn.conflicts = F))
suppressPackageStartupMessages(library("FSelectorRcpp", quietly = T, verbose = F, warn.conflicts = F))
suppressPackageStartupMessages(library(colino, quietly = T, verbose = F, warn.conflicts = F))
suppressPackageStartupMessages(library(argparse, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(parallel, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(parallelly, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(stringr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(logger, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(collinear, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(earth, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(kernlab, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(stacks, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(baguette, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
# these are the test dependencies
suppressPackageStartupMessages(library(testthat, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(covr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(remotes, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))


