## Library requirements
library(janitor, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(tidyr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(tibble, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(progress, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(data.tree, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(dplyr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)
library(corrr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(tibble, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(purrr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
suppressPackageStartupMessages(library(ranger, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
library(readr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(vroom, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(tidyselect, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(recipes, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
suppressPackageStartupMessages(library(ggplot2, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(tidymodels, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
library(fastshap, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(shapviz, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
suppressPackageStartupMessages(library(doParallel, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
library(foreach, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(doParallel, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
suppressPackageStartupMessages(library(glmnet, quietly = T, verbose = F, warn.conflicts = F))
library("FSelectorRcpp", quietly = T, verbose = F, warn.conflicts = F)
library(colino, quietly = T, verbose = F, warn.conflicts = F)
suppressPackageStartupMessages(library(argparse, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(parallel, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(parallelly, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE))
library(stringr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
# these are the test dependencies
library(testthat, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(covr, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(remotes, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)
library(logger, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)

