name: Actions Test
run-name: Testing ${{ github.ref }}
on: [push]
jobs:
  load-r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install needed libraries
        if: runner.os == 'Linux'
        run: sudo apt update -y && sudo apt install -y libz-dev libxml2-dev
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install test dependencies
        run: |
          install.packages("remotes")
          remotes::install_cran("covr")
          install.packages("testthat")
        shell: Rscript {0}
      
      - name: Test coverage
        run: |
          covr::file_coverage("tree.R", "tests/test-tree.R")
        shell: Rscript {0}