name: Test
run-name: Testing ${{ github.ref }}
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install needed libraries
        if: runner.os == 'Linux'
        run: sudo apt update -y && sudo apt install -y libz-dev libxml2-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "renv"

      - uses: r-lib/actions/setup-renv@v2

      # goal is to match a single file of functions with a tests file, to generate coverage
      - name: Test coverage
        run: |
          covr::file_coverage(c("lib/options.R", "lib/validators.R"), c("tests/test_options.R", "tests/test_validators.R"))
        shell: Rscript {0}
